rule pyani:
    input:
        genomes="genomes/",
    output:
        tsv="pyani.tsv",
    params:
        method="anim",
        pyanidb="pyanidb",
        outdir="outdir",
    threads: 1
    wrapper:
        "https://github.com/Hocnonsense/snakemake-wrappers/raw/hwrn/bio/pyani/ani2tsv"
